version: '3'

tasks:
  default:
    cmds:
      - task: backend:server
      - task: frontend:dev

  backend:server:
    dir: backend
    cmds:
      - make server

  backend:test:
    dir: backend
    cmds:
      - make test

  backend:build:
    dir: backend
    cmds:
      - go build -o bin/main main.go

  frontend:dev:
    dir: frontend
    cmds:
      - source ~/.nvm/nvm.sh && nvm use 22 && bun run dev

  frontend:build:
    dir: frontend
    cmds:
      - source ~/.nvm/nvm.sh && nvm use 22 && bun run build

  frontend:install:
    dir: frontend
    cmds:
      - source ~/.nvm/nvm.sh && nvm use 22 && bun install

  install:
    cmds:
      - task: frontend:install
      - cd backend && go mod download

  build:
    cmds:
      - task: backend:build
      - task: frontend:build
