# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  # เพิ่มตรงนี้: เพื่อให้พิมพ์แค่คำสั่ง `task` เปล่าๆ แล้วทำงานได้เลย
  default:
    cmds:
      - task: dev

  dev:
    cmds:
      - task: open-tools
      - task: start-servers
    
  open-tools:
    desc: "เปิด VS Code และเว็บเบราว์เซอร์"
    cmds:
      - code .
      - cmd: open "http://localhost:8000"
#  && open "http://localhost:8000/docs"

  start-servers:
    desc: "รัน Backend"
    cmds: 
      - make server