// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: like.sql

package db

import (
	"context"
)

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
    user_id,
    post_id
) VALUES (
    $1, $2
) RETURNING user_id, post_id, created_at
`

type CreateLikeParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, createLike, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE user_id = $1 AND post_id = $2
`

type DeleteLikeParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.UserID, arg.PostID)
	return err
}

const getLike = `-- name: GetLike :one
SELECT user_id, post_id, created_at FROM likes
WHERE user_id = $1 AND post_id = $2 LIMIT 1
`

type GetLikeParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) GetLike(ctx context.Context, arg GetLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, getLike, arg.UserID, arg.PostID)
	var i Like
	err := row.Scan(&i.UserID, &i.PostID, &i.CreatedAt)
	return i, err
}

const listLikesByPost = `-- name: ListLikesByPost :many
SELECT user_id, post_id, created_at FROM likes
WHERE post_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListLikesByPostParams struct {
	PostID int64 `json:"post_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLikesByPost(ctx context.Context, arg ListLikesByPostParams) ([]Like, error) {
	rows, err := q.db.Query(ctx, listLikesByPost, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(&i.UserID, &i.PostID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikesByUser = `-- name: ListLikesByUser :many
SELECT user_id, post_id, created_at FROM likes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListLikesByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLikesByUser(ctx context.Context, arg ListLikesByUserParams) ([]Like, error) {
	rows, err := q.db.Query(ctx, listLikesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(&i.UserID, &i.PostID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
