// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    author_id,
    content,
    parent_id,
    repost_of_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, author_id, content, parent_id, repost_of_id, reply_count, like_count, repost_count, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	AuthorID   int64       `json:"author_id"`
	Content    pgtype.Text `json:"content"`
	ParentID   pgtype.Int8 `json:"parent_id"`
	RepostOfID pgtype.Int8 `json:"repost_of_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.Content,
		arg.ParentID,
		arg.RepostOfID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.RepostOfID,
		&i.ReplyCount,
		&i.LikeCount,
		&i.RepostCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
UPDATE posts
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, author_id, content, parent_id, repost_of_id, reply_count, like_count, repost_count, created_at, updated_at, deleted_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.RepostOfID,
		&i.ReplyCount,
		&i.LikeCount,
		&i.RepostCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, author_id, content, parent_id, repost_of_id, reply_count, like_count, repost_count, created_at, updated_at, deleted_at FROM posts
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.ParentID,
			&i.RepostOfID,
			&i.ReplyCount,
			&i.LikeCount,
			&i.RepostCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    content = COALESCE($2, content),
    reply_count = COALESCE($3, reply_count),
    like_count = COALESCE($4, like_count),
    repost_count = COALESCE($5, repost_count),
    updated_at = now()
WHERE id = $1
RETURNING id, author_id, content, parent_id, repost_of_id, reply_count, like_count, repost_count, created_at, updated_at, deleted_at
`

type UpdatePostParams struct {
	ID          int64       `json:"id"`
	Content     pgtype.Text `json:"content"`
	ReplyCount  pgtype.Int4 `json:"reply_count"`
	LikeCount   pgtype.Int4 `json:"like_count"`
	RepostCount pgtype.Int4 `json:"repost_count"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Content,
		arg.ReplyCount,
		arg.LikeCount,
		arg.RepostCount,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.RepostOfID,
		&i.ReplyCount,
		&i.LikeCount,
		&i.RepostCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
