// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	GetLike(ctx context.Context, arg GetLikeParams) (Like, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
