CREATE TYPE "notification_type" AS ENUM (
  'follow',
  'like',
  'reply',
  'repost',
  'quote',
  'mention'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(30) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "display_name" varchar(50),
  "bio" varchar(160),
  "avatar_url" text,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token_hash" text UNIQUE NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "follows" (
  "follower_id" bigint NOT NULL,
  "following_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("follower_id", "following_id")
);

CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_id" bigint NOT NULL,
  "content" varchar(280),
  "parent_id" bigint,
  "repost_of_id" bigint,
  "reply_count" int NOT NULL DEFAULT 0,
  "like_count" int NOT NULL DEFAULT 0,
  "repost_count" int NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

CREATE TABLE "likes" (
  "user_id" bigint NOT NULL,
  "post_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("user_id", "post_id")
);

CREATE TABLE "media" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" bigint NOT NULL,
  "url" text NOT NULL,
  "type" varchar(20) NOT NULL,
  "position" smallint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "hashtags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tag" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "post_hashtags" (
  "post_id" bigint NOT NULL,
  "hashtag_id" bigint NOT NULL,
  PRIMARY KEY ("post_id", "hashtag_id")
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_id" bigint NOT NULL,
  "actor_id" bigint NOT NULL,
  "type" notification_type NOT NULL,
  "post_id" bigint,
  "read_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "refresh_tokens" ("user_id");

CREATE INDEX ON "follows" ("following_id");

CREATE INDEX ON "posts" ("author_id", "id");

CREATE INDEX ON "posts" ("parent_id");

CREATE INDEX ON "posts" ("repost_of_id");

CREATE INDEX ON "posts" ("created_at");

CREATE INDEX ON "likes" ("post_id");

CREATE INDEX ON "media" ("post_id");

CREATE INDEX ON "post_hashtags" ("hashtag_id");

CREATE INDEX ON "notifications" ("recipient_id", "id");

COMMENT ON COLUMN "posts"."parent_id" IS 'set when this is a reply';

COMMENT ON COLUMN "posts"."repost_of_id" IS 'set for repost / quote';

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("following_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("parent_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("repost_of_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "likes" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "media" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_hashtags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_hashtags" ADD FOREIGN KEY ("hashtag_id") REFERENCES "hashtags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
