// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationType string

const (
	NotificationTypeFollow  NotificationType = "follow"
	NotificationTypeLike    NotificationType = "like"
	NotificationTypeReply   NotificationType = "reply"
	NotificationTypeRepost  NotificationType = "repost"
	NotificationTypeQuote   NotificationType = "quote"
	NotificationTypeMention NotificationType = "mention"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Follow struct {
	FollowerID  int64              `json:"follower_id"`
	FollowingID int64              `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Hashtag struct {
	ID  int64  `json:"id"`
	Tag string `json:"tag"`
}

type Like struct {
	UserID    int64              `json:"user_id"`
	PostID    int64              `json:"post_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Medium struct {
	ID        int64              `json:"id"`
	PostID    int64              `json:"post_id"`
	Url       string             `json:"url"`
	Type      string             `json:"type"`
	Position  int16              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID          int64              `json:"id"`
	RecipientID int64              `json:"recipient_id"`
	ActorID     int64              `json:"actor_id"`
	Type        NotificationType   `json:"type"`
	PostID      pgtype.Int8        `json:"post_id"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID       int64       `json:"id"`
	AuthorID int64       `json:"author_id"`
	Content  pgtype.Text `json:"content"`
	// set when this is a reply
	ParentID pgtype.Int8 `json:"parent_id"`
	// set for repost / quote
	RepostOfID  pgtype.Int8        `json:"repost_of_id"`
	ReplyCount  int32              `json:"reply_count"`
	LikeCount   int32              `json:"like_count"`
	RepostCount int32              `json:"repost_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PostHashtag struct {
	PostID    int64 `json:"post_id"`
	HashtagID int64 `json:"hashtag_id"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Bio          pgtype.Text        `json:"bio"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
