// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeletePost(ctx context.Context, id int64) error
	GetLike(ctx context.Context, arg GetLikeParams) (Like, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListLikesByPost(ctx context.Context, arg ListLikesByPostParams) ([]Like, error)
	ListLikesByUser(ctx context.Context, arg ListLikesByUserParams) ([]Like, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
